### PR TITLE
First try to add  BSC support

### PR DESCRIPTION
**Pull request by feraudet**
Hello,
I get those error, where am I wrong ? I see no other place where other chains are defined
> Task :compileKotlin FAILED
> e: /app/src/main/kotlin/io/emeraldpay/dshackle/Global.kt: (61, 28): Unresolved reference: BSC
> e: /app/src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethods.kt: (146, 27): Unresolved reference: BSC
> e: /app/src/main/kotlin/io/emeraldpay/dshackle/upstream/calls/DefaultEthereumMethods.kt: (178, 27): Unresolved reference: BSC
> FAILURE: Build failed with an exception.

#146

### CODE REVIEW

**Comment by feraudet** [comment]
> Hi @feraudet, did you ever solve this?
> 
> Cheers

Unfortunately no ...

**Comment by vandot** [comment]
@feraudet you are missing reference in `emerald-grpc` [here](https://github.com/emeraldpay/emerald-grpc/blob/master/proto/common.proto#L18)

**Comment by lukoyanov** [comment]
Also interested in BSC support, it would be great to see this PR merged.

**Comment by OscBacon** [comment]
Hey, any updates on what's blocking this?

**Comment by splix** [comment]
Unfortunately, I don't think we have any resources available to support any additional chains including BSC. We consider providing this on a commercial basis, thought, if there is any interest. You can contact me by splix@emerald.cash if you're interested

**Comment by OscBacon** [comment]
What exactly is missing ? Might be good to reopen and let others have a go at it

**Comment by splix** [comment]
Well, I mean we have to maintain the code specifics for the BSC if it's added and accept/fix bugs related to BSC, forever. That's a big commitment. Also run nodes for testing, etc.

**Pull request closed without merging**
