### PR TITLE
allow configuring methods with static responses

### PR DESCRIPTION
**Pull request by skylenet**
Haven't touched Java for 8 years. And I thought that I would be able to live without JDK on my machine, haha. This is also the first time I'm looking at Kotlin :see_no_evil: .. so bear with me. I'm not sure if I'm changing code at the right places, so any help is really appreciated! :) 

The idea would be that we could have static method responses via configuration. This could be a workaround for https://github.com/emeraldpay/dshackle/issues/96 

Example:

```yaml
# config
cluster:
  upstreams:
    - id: geth-0
      chain: ethereum
      methods:
        enabled:
          - name: eth_chainId
            static: "0x1467f3"  # static return value
          - name: net_version
            static: "1337331"  # static return value
 ...
```

### CODE REVIEW

**Comment by splix** [comment]
That's interesting! Thank you, @skylenet. 

In general I was thinking about more complex design for custom chains, to make it working with grpc protocol, caching, etc. But this workaround seems to be doing all you need in your situation. I like the simplicity of the solution. And I can imagine _static_ methods working in other situations.

So, if it works in your setup I can merge it. But I would ask you to mention it in docs: in `reference-configuration.adoc` and optionally in `04-upstream-config.adoc`. Thank you

**Comment by splix** [comment]
I guess I'll need to move it to a separate config section later. Because it's not really a config for an upstream, even opposite. So later I'll introduce a new section for this and other _per-chain_ options. But for now I don't any better place to put it. If you willing to do it now, I mean start a separate section for general chain options, I'd appreciate too.

**Comment by skylenet** [comment]
@splix I've updated the docs to reflect the possibility of overwriting or adding new static methods to upstreams. I think what you said, regarding having *per-chain* options also makes sense and that could be provided on another PR. I think that both options are valid and useful in their own ways. I don't have the time right now to deal with that, learning Kotlin and going to deep into the codebase wasn't part of my plans :P

**Comment by splix** [comment]
Sure, thank you! 

Can you confirm it fully works for your setup and can be merged now?

**Comment by skylenet** [comment]
@splix I've just built the docker image now and tried it out on a running system with 10 upstreams and it's working fine :+1: 

```
curl --request POST 'http://localhost:8001/api/v1/namespaces/ethereum-private/services/dshackle:8545/proxy/eth' \ 
--header 'Content-Type: application/json' \
--data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_chainId",
        "params":[],
        "id":1
}'
{"jsonrpc":"2.0","id":1,"result":"0x1467f3"}
```

**Comment by splix** [comment]
That's great, thank you! Merging it then

**Pull request merged**
